// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: gozab.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Vec) Reset() {
	*x = Vec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec) ProtoMessage() {}

func (x *Vec) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec.ProtoReflect.Descriptor instead.
func (*Vec) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{0}
}

func (x *Vec) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Vec) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Zxid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch   int32 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Counter int32 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *Zxid) Reset() {
	*x = Zxid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zxid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zxid) ProtoMessage() {}

func (x *Zxid) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zxid.ProtoReflect.Descriptor instead.
func (*Zxid) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{1}
}

func (x *Zxid) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Zxid) GetCounter() int32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type Txn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V *Vec  `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Z *Zxid `protobuf:"bytes,2,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Txn) Reset() {
	*x = Txn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn) ProtoMessage() {}

func (x *Txn) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn.ProtoReflect.Descriptor instead.
func (*Txn) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{2}
}

func (x *Txn) GetV() *Vec {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *Txn) GetZ() *Zxid {
	if x != nil {
		return x.Z
	}
	return nil
}

type PropTxn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E           int32 `protobuf:"varint,1,opt,name=e,proto3" json:"e,omitempty"`
	Transaction *Txn  `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *PropTxn) Reset() {
	*x = PropTxn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropTxn) ProtoMessage() {}

func (x *PropTxn) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropTxn.ProtoReflect.Descriptor instead.
func (*PropTxn) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{3}
}

func (x *PropTxn) GetE() int32 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *PropTxn) GetTransaction() *Txn {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type AckTxn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AckTxn) Reset() {
	*x = AckTxn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckTxn) ProtoMessage() {}

func (x *AckTxn) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckTxn.ProtoReflect.Descriptor instead.
func (*AckTxn) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{4}
}

func (x *AckTxn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CommitTxn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CommitTxn) Reset() {
	*x = CommitTxn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxn) ProtoMessage() {}

func (x *CommitTxn) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxn.ProtoReflect.Descriptor instead.
func (*CommitTxn) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{5}
}

func (x *CommitTxn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gozab_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_gozab_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_gozab_proto_rawDescGZIP(), []int{6}
}

func (x *Empty) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_gozab_proto protoreflect.FileDescriptor

var file_gozab_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x6f, 0x7a, 0x61, 0x62, 0x22, 0x2d, 0x0a, 0x03, 0x56, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x04, 0x5a, 0x78, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x3a, 0x0a, 0x03, 0x54,
	0x78, 0x6e, 0x12, 0x18, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x56, 0x65, 0x63, 0x52, 0x01, 0x76, 0x12, 0x19, 0x0a, 0x01,
	0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e,
	0x5a, 0x78, 0x69, 0x64, 0x52, 0x01, 0x7a, 0x22, 0x45, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x70, 0x54,
	0x78, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x65,
	0x12, 0x2c, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x54, 0x78,
	0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x22,
	0x0a, 0x06, 0x41, 0x63, 0x6b, 0x54, 0x78, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x25, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x78, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x66, 0x0a, 0x0a,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x09, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x70, 0x54, 0x78, 0x6e, 0x1a, 0x0d, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e,
	0x41, 0x63, 0x6b, 0x54, 0x78, 0x6e, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x12, 0x10, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x54, 0x78, 0x6e, 0x1a, 0x0c, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x32, 0x3a, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0a, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x56, 0x65, 0x63,
	0x1a, 0x0c, 0x2e, 0x67, 0x6f, 0x7a, 0x61, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gozab_proto_rawDescOnce sync.Once
	file_gozab_proto_rawDescData = file_gozab_proto_rawDesc
)

func file_gozab_proto_rawDescGZIP() []byte {
	file_gozab_proto_rawDescOnce.Do(func() {
		file_gozab_proto_rawDescData = protoimpl.X.CompressGZIP(file_gozab_proto_rawDescData)
	})
	return file_gozab_proto_rawDescData
}

var file_gozab_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gozab_proto_goTypes = []interface{}{
	(*Vec)(nil),       // 0: gozab.Vec
	(*Zxid)(nil),      // 1: gozab.Zxid
	(*Txn)(nil),       // 2: gozab.Txn
	(*PropTxn)(nil),   // 3: gozab.PropTxn
	(*AckTxn)(nil),    // 4: gozab.AckTxn
	(*CommitTxn)(nil), // 5: gozab.CommitTxn
	(*Empty)(nil),     // 6: gozab.Empty
}
var file_gozab_proto_depIdxs = []int32{
	0, // 0: gozab.Txn.v:type_name -> gozab.Vec
	1, // 1: gozab.Txn.z:type_name -> gozab.Zxid
	2, // 2: gozab.PropTxn.transaction:type_name -> gozab.Txn
	3, // 3: gozab.Simulation.Broadcast:input_type -> gozab.PropTxn
	5, // 4: gozab.Simulation.Commit:input_type -> gozab.CommitTxn
	0, // 5: gozab.ClientConsole.SendRequest:input_type -> gozab.Vec
	4, // 6: gozab.Simulation.Broadcast:output_type -> gozab.AckTxn
	6, // 7: gozab.Simulation.Commit:output_type -> gozab.Empty
	6, // 8: gozab.ClientConsole.SendRequest:output_type -> gozab.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gozab_proto_init() }
func file_gozab_proto_init() {
	if File_gozab_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gozab_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gozab_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zxid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gozab_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gozab_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropTxn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gozab_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckTxn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gozab_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTxn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gozab_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gozab_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gozab_proto_goTypes,
		DependencyIndexes: file_gozab_proto_depIdxs,
		MessageInfos:      file_gozab_proto_msgTypes,
	}.Build()
	File_gozab_proto = out.File
	file_gozab_proto_rawDesc = nil
	file_gozab_proto_goTypes = nil
	file_gozab_proto_depIdxs = nil
}
